apiVersion: apps/v1
kind: Deployment
metadata:
  name: plato-ubs-sc-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plato-ubs-sc-genai
  template:
    metadata:
      labels:
        app: plato-ubs-sc-genai
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      serviceAccountName: plato-ubs-sc-genai
      containers:
      - name: plato-ubs-sc-genai
        image: plato-ubs-sc-genai
        workingDir: /app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: plato-ubs-sc-genai
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: plato-ubs-sc-genai